accelerate launch --num_cpu_threads_per_process 1 sdxl_train_network.py \
    --pretrained_model_name_or_path=models/leosam.safetensors \
    --dataset_config=_typos.toml \
    --output_dir=output/locon-leosam-cropped_face_1024_1024-8-4e-4-reg-2000\
    --output_name=test \
    --max_train_steps=2000 \
    --save_model_as=safetensors \
    --prior_loss_weight=1.0 \
    --learning_rate=4e-4 \
    --lr_scheduler="linear" \
    --optimizer_type="Adafactor" \
    --optimizer_args scale_parameter=False relative_step=False warmup_init=False \
    --xformers \
    --mixed_precision="fp16" \
    --cache_latents \
    --text_encoder_lr=4e-4 \
    --gradient_checkpointing \
    --save_every_n_steps=500 \
    --sample_every_n_steps=200 \
    --sample_sampler=euler_a \
    --sample_prompts="sample_prompt.json"\
    --no_half_vae \
    --network_dim=4 \
    --network_args "conv_dim=4" "conv_alpha=1.0" "algo=locon"\
    --network_module=lycoris.kohya
